# Generated by Django 4.1.2 on 2022-11-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0007_alter_reviews_approved_alter_reviews_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='slug',
        ),
    ]
