# Generated by Django 4.1.2 on 2022-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0010_rename_clening_type_bookingsystem_cleaning_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystem',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Confirmed')], default=0),
        ),
    ]
