# Generated by Django 4.1.2 on 2022-11-07 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0011_bookingsystem_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingsystem',
            options={'ordering': ['-booked']},
        ),
    ]
