# Generated by Django 4.1.2 on 2022-11-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0012_alter_bookingsystem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_type',
            field=models.IntegerField(choices=[(0, 'Deep Cleaning'), (1, 'General Cleaning')], default=''),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='time_slot',
            field=models.IntegerField(choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30')], default=''),
        ),
    ]
