# Generated by Django 4.1.2 on 2022-11-07 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cleaning', '0013_alter_bookingsystem_cleaning_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Deep Cleaning'), (1, 'General Cleaning')]),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='time_slot',
            field=models.IntegerField(blank=True, choices=[(0, '09:00 – 09:30'), (1, '10:00 – 10:30'), (2, '11:00 – 11:30'), (3, '12:00 – 12:30'), (4, '13:00 – 13:30'), (5, '14:00 – 14:30'), (6, '15:00 – 15:30'), (7, '16:00 – 16:30')]),
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, max_length=400)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
