# Generated by Django 4.1.2 on 2022-11-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0015_questionnaire_asked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='stauts',
            field=models.IntegerField(choices=[(0, 'Not answered'), (1, 'Answered')], default=0),
        ),
    ]
