# Generated by Django 4.1.2 on 2022-11-08 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0016_questionnaire_stauts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='stauts',
            new_name='status',
        ),
    ]
