# Generated by Django 4.1.2 on 2022-11-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0022_alter_bookingsystem_cleaning_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
