# Generated by Django 4.1.2 on 2022-11-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0023_reviews_updated'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionnaire',
        ),
    ]
