# Generated by Django 4.1.2 on 2022-11-13 11:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0024_delete_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today)]),
        ),
    ]
