# Generated by Django 4.1.2 on 2022-11-13 14:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0025_alter_bookingsystem_cleaning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date.today, 'Time cannot be in the Past')]),
        ),
    ]
