# Generated by Django 4.1.2 on 2022-11-13 23:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0026_alter_bookingsystem_cleaning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
