# Generated by Django 4.1.2 on 2022-11-14 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0027_alter_reviews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
