# Generated by Django 4.1.2 on 2022-11-22 21:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0032_alter_bookingsystem_cleaning_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingsystem',
            name='cleaning_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 11, 23), 'Booking cannot be in the Past, or the Same Day!')]),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='status',
            field=models.BooleanField(choices=[(0, 'Pending'), (1, 'Approved')], default=0),
        ),
    ]
